#!/usr/bin/env python3
import sh
import socket

# Get the hostname of the machine
hostname = socket.gethostname()


def send_message(msg):
    telegram_send = sh.telegram_send.bake(msg)
    try:
        telegram_send()
    except sh.ErrorReturnCode_1 as e:
        print(f"Error sending Telegram message: {e}")

def main():
    # Execute `df -h | grep /md`
    df_output = sh.grep(sh.df('-h'), '/md')
    send_message(f":{hostname}\n{df_output}")

if __name__ == "__main__":
    main()
