#!/usr/bin/env python3

import os
import re
import sh

def test_file(file):
    print(f"Testing file: '{file}'")
    try:
        output = sh.unrar('t', '-c-', file)
        print(output)
    except sh.ErrorReturnCode as e:
        print(f"Test and recover rar file: '{file}' failed")
        return False
    return True

def extract_file(file):
    print(f"Extracting file: '{file}'")
    try:
        output = sh.unrar('x', '-c-', file)
        print(output)
    except sh.ErrorReturnCode as e:
        print(f"Extraction of file: '{file}' failed")
        return False
    return True

def delete_files(file):
    print("Printing Regex")
    to_delete = re.sub(r'.part.*$', '', file).replace('./', '')
    to_delete_regex = f".*({to_delete}){{1}}.*\.(rar|rev)"
    print(f"regex: {to_delete_regex}")

    files_to_delete = [f for f in os.listdir('.') if re.match(to_delete_regex, f)]

    for f_del in files_to_delete:
        print(f"deleting '{f_del}'")
        os.remove(f_del)

def find_files():
    files_dict = {}
    for f in os.listdir('.'):
        match = re.match(r'^(.*\.part)([0-9]*)(\.rar|\.rev)$', f)
        if match:
            base_name, part_number, extension = match.groups()
            part_number = int(part_number)
            if base_name not in files_dict or part_number < files_dict[base_name][1]:
                files_dict[base_name] = (f, part_number)
    return [f[0] for f in files_dict.values()]

def unrar_all():
    print("Unrar All file starting from number part[0].rar")

    files = find_files()

    print(f"{len(files)} file(s) found")

    for file in files:
        print(f"File to elaborate: '{file}'")

        if not test_file(file):
            return 1

        if extract_file(file):
            delete_files(file)
        else:
            return 1

    return 0

if __name__ == "__main__":
    exit_code = unrar_all()
    exit(exit_code)
